// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unrkuuxtkuozvesfgxsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucmt1dXh0a3VvenZlc2ZneHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDA4NjAsImV4cCI6MjA1OTUxNjg2MH0.H8kjiCaRJZXtUvaQyBn0E1Tg5ibercnTIlmY496a0JQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);