// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmbqklcryzpyapbkkkgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttYnFrbGNyeXpweWFwYmtra2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODMxOTksImV4cCI6MjA2MDU1OTE5OX0.Tbp0YpbHm_gc8nG_EMNfIhYAoDapwjgoPEdNYs96CGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);